<?php
# --- Initialize .env Loader ---
require_once __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

# --- Database Configuration (Reading from $_ENV) ---
$wgDBtype = $_ENV['MW_DB_TYPE'] ?? 'mysql';
$wgDBserver = $_ENV['MW_DB_SERVER'] ?? 'localhost';
$wgDBname = $_ENV['MW_DB_NAME'] ?? null;
$wgDBuser = $_ENV['MW_DB_USER'] ?? null;
$wgDBpassword = $_ENV['MW_DB_PASSWORD'] ?? null;
$wgDBprefix = $_ENV['MW_DB_PREFIX'] ?? '';
$wgDBssl = filter_var($_ENV['MW_DB_SSL'] ?? false, FILTER_VALIDATE_BOOLEAN);

# --- Cryptographic Keys ---
$wgSecretKey  = $_ENV['MW_SECRET_KEY'] ?? '';
$wgUpgradeKey = $_ENV['MW_UPGRADE_KEY'] ?? '';

# --- Email Senders ---
$wgConfirmAccountContact = $_ENV['MW_CONFIRM_ACCOUNT_CONTACT'];
$wgPasswordSender = $_ENV['MW_PASSWORD_SENDER'];

# --- SMTP Configuration ---
if (getenv('MW_SMTP_HOST')) {
    $wgEnableEmail = true;
    $wgEnableUserEmail = true;

    $wgSMTP = [
        'host'      => getenv('MW_SMTP_HOST'),
        'IDHost'    => getenv('MW_SMTP_IDHOST') ?: parse_url($wgServer, PHP_URL_HOST),
        'localhost' => getenv('MW_SMTP_LOCALHOST') ?: parse_url($wgServer, PHP_URL_HOST),
        'port'      => (int)getenv('MW_SMTP_PORT'),
        'auth'      => filter_var(getenv('MW_SMTP_AUTH'), FILTER_VALIDATE_BOOLEAN),
        'username'  => getenv('MW_SMTP_USERNAME'),
        'password'  => getenv('MW_SMTP_PASSWORD')
    ];
}

# This file was automatically generated by the MediaWiki 1.41.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = 'Deoband Community Wikimedia';
$wgMetaNamespace = "DCW";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/dcwwiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://dcwwiki.org";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!

$wgLogos = [
	'1x' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",		// path to 1x version
	'1.5x' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",	// path to 1.5x version
	'2x' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",		// path to 2x version
	'svg' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",		// path to svg version
	'icon' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",			// A version of the logo without wordmark and tagline
	'wordmark' => [
		'src' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",	// path to wordmark version
		'1x' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",		// optional if you want to support browsers with SVG support with an SVG logo.
		'width' => 135,
		'height' => 135,
	],
	'tagline' => [
		'src' => "{$wgUploadPath}/dcwwiki/images/5/56/DCW_logo.png",		// path to tagline version
		'width' => 135,
		'height' => 135,
	],
];

$wgFavicon = "{$wgUploadPath}/dcwwiki/images/4/40/DCW_logo.svg";
## UPO means: this is also a user preference option

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];


$wgAllowTitlesInSVG = true;
$wgSVGConverter = 'ImageMagick';

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgUploadNavigationUrl = '/Special:UploadWizard';
wfLoadExtension( 'UploadWizard' );
$wgUploadWizardConfig = [
	'debug' => false,
	'autoAdd' => [
	 	'categories' => [
	 		 'Uploaded with UploadWizard'	
	 		 ],
		], // Should be localised to the language of your wiki instance
	'altUploadForm' => 'Special:Upload',
	'feedbackLink' => false, // Disable the link for feedback (default: points to Commons)
	'alternativeUploadToolsPage' => false, // Disable the link to alternative upload tools (default: points to Commons)
	'enableFormData' => true, // Enable FileAPI uploads be used on supported browsers
	'enableMultipleFiles' => true,
	'enableMultiFileSelect' => false,
	'uwLanguages' => [
		'en' => 'English'
		], // Selectable languages for file descriptions - defaults to 'en'
	'tutorial' => [
	 	'skip' => true
		], // Skip the tutorial
	'maxUploads' => 10, // Number of uploads with one form - defaults to 50
	];
# Add new types to the existing list from DefaultSettings.php
$wgFileExtensions = array_merge(
    $wgFileExtensions, [
        'pdf', 'ppt', 'jp2', 'doc', 'docx', 'xls', 'xlsx'
    ]
    );
$wgStrictFileExtensions = false;

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = 'en';


# Time zone

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";



## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "WMAU";
$wgDefaultMobileSkin = "WMAU";
# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );
wfLoadSkin( 'WMAU' );


# End of automatically generated settings.
# Add more configuration options below.
/* Etensions here */
wfLoadExtension( 'WikidataPageBanner' );
$wgWPBEnablePageImagesBanners = true;
$wgWPBEnableMainPage = true;
$wgShowExceptionDetails = false;
$wgMainCacheType = CACHE_DB;
// To grant sysops permissions to edit interwiki data
$wgGroupPermissions['sysop']['interwiki'] = true;
$wgRestrictDisplayTitle = true;

wfLoadExtension( 'Poem' );
wfLoadExtension( 'NoTitle' );
wfLoadExtension( 'Cargo' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'UploadWizard' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'TitleKey' );
wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'RenderThumbnails' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'PageForms' );
wfLoadExtension( 'WikiSEO' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'MobileDetect' );
wfLoadExtension( 'YouTube' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'RealMe' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'UrlShortener' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'SecurePoll' );
wfLoadExtension( 'NamespaceManager' );
wfLoadExtension( 'LookupUser' );
wfLoadExtension( 'Babel' );
wfLoadExtension( 'RealMe' );
wfLoadExtension( 'cldr' );
wfLoadExtension( 'LinkCards' );
wfLoadExtension( 'CampaignEvents' );
wfLoadExtension( 'CommunityConfiguration' );
wfLoadExtension( 'Scribunto' );
$wgScribuntoDefaultEngine = 'luastandalone';
wfLoadExtension( 'Translate' );

$wgDefaultUserOptions['usenewrc'] = 1;

$wgGroupPermissions['user']['translate-messagereview'] = false;
$wgGroupPermissions['user']['translate-groupreview'] = false;
$wgGroupPermissions['user']['translate-import'] = false;
$wgGroupPermissions['sysop']['pagetranslation'] = true;
$wgGroupPermissions['sysop']['translate-manage'] = true;
$wgTranslateDocumentationLanguageCode = 'qqq';
$wgExtraLanguageNames['qqq'] = 'Message documentation'; # No linguistic content. Used for documenting messages
    $wgPageLanguageUseDB = true;
  $wgGroupPermissions['sysop']['pagelang'] = true;

wfLoadExtension( 'UniversalLanguageSelector' );
$wgUseFileCache = true;

/* Editing priveleges go below this line */
$wgStaffEditsMessagePrefix = 'dcw';
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['listusers'] = false;
$wgGroupPermissions['user']['listusers'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['createtalk'] = false;


$wgGroupPermissions['user']['createpage'] = false;
$wgGroupPermissions['user']['createclass'] = false;
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['movefile'] = false;
$wgGroupPermissions['user']['move-categorypages'] = false;
$wgGroupPermissions['user']['move-subpages'] = false;
$wgGroupPermissions['user']['move-rootuserpages'] = false;
$wgGroupPermissions['user']['reupload-shared'] = false;
$wgGroupPermissions['user']['reupload'] = false;
$wgGroupPermissions['user']['sendemail'] = false;
$wgGroupPermissions['user']['createtalk'] = false;
$wgGroupPermissions['user']['applychangetags'] = false;
$wgGroupPermissions['user']['changetags'] = false;
$wgGroupPermissions['user']['upload'] = false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['user']['multipageedit'] = false;
$wgGroupPermissions['user']['editcontentmodel'] = false;
$wgGroupPermissions['user']['campaignevents-enable-registration'] = false;
$wgGroupPermissions['user']['campaignevents-delete-registration'] = false;
$wgGroupPermissions['user']['campaignevents-organize-events'] = false;
$wgGroupPermissions['user']['campaignevents-email-participants'] = false;
$wgGroupPermissions['*']['viewsuppressed'] = false;


/* Admin priveleges */
$wgGroupPermissions['sysop']['sendemail'] = true;
$wgGroupPermissions['sysop']['upwizcampaigns'] = false;
$wgGroupPermissions['sysop']['deleterevision'] = true;
$wgGroupPermissions['sysop']['deletelogentry'] = true;
$wgGroupPermissions['sysop']['createpage'] = true;
$wgGroupPermissions['sysop']['dcw-staff'] = false;
$wgGroupPermissions['sysop']['campaignevents-enable-registration'] = true;
$wgGroupPermissions['sysop']['campaignevents-delete-registration'] = true;
$wgGroupPermissions['sysop']['campaignevents-organize-events'] = true;
$wgGroupPermissions['sysop']['campaignevents-email-participants'] = true;

/* Staff priveleges */
$wgGroupPermissions['dcw-staff']['sendemail'] = true;
$wgGroupPermissions['dcw-staff']['staffedit'] = true;
$wgGroupPermissions['dcw-staff']['createpage'] = true;
$wgGroupPermissions['dcw-staff']['lookupuser'] = true;
$wgGroupPermissions['dcw-staff']['edit'] = true;
$wgGroupPermissions['dcw-staff']['protect'] = true;
$wgGroupPermissions['dcw-staff']['move'] = true;
$wgGroupPermissions['dcw-staff']['editprotected'] = true;
$wgGroupPermissions['dcw-staff']['edit-policy'] = true;
$wgGroupPermissions['dcw-staff']['edit-main'] = true;
$wgNamespaceProtection[NS_MAIN] = array( 'edit-main' );
$wgGroupPermissions['dcw-staff']['deletelogentry'] = true;
$wgGroupPermissions['dcw-staff']['deleterevision'] = true;
$wgGroupPermissions['dcw-staff']['suppressionlog'] = true;
$wgGroupPermissions['dcw-staff']['viewsuppressed'] = true;
$wgGroupPermissions['dcw-staff']['suppressrevision'] = true;
$wgGroupPermissions['dcw-staff']['movefile'] = true;
$wgGroupPermissions['dcw-staff']['createtalk'] = true;
$wgGroupPermissions['dcw-staff']['userrights'] = true;
$wgGroupPermissions['dcw-staff']['usermerge'] = true;
$wgGroupPermissions['dcw-staff']['renameuser'] = true;
$wgGroupPermissions['dcw-staff']['createaccount'] = true;
$wgGroupPermissions['dcw-staff']['noratelimit'] = true;
$wgGroupPermissions['dcw-staff']['requestips'] = true;
$wgGroupPermissions['dcw-staff']['confirmaccount'] = true;
$wgGroupPermissions['dcw-staff']['lookupcredentials'] = true;

/* Board */
$wgRestrictionLevels[] = 'edit-dcw-board'; 
$wgGroupPermissions['dcw-board']['sendemail'] = true;
$wgGroupPermissions['dcw-board']['createpage'] = true;
$wgGroupPermissions['dcw-board']['hideuser'] = true;
$wgGroupPermissions['dcw-board']['deletelogentry'] = true;
$wgGroupPermissions['dcw-board']['deleterevision'] = true;
$wgGroupPermissions['dcw-board']['suppressionlog'] = true;
$wgGroupPermissions['dcw-board']['viewsuppressed'] = true;
$wgGroupPermissions['dcw-board']['suppressrevision'] = true;
$wgGroupPermissions['dcw-board']['edit-dcw-board'] = true;
$wgGroupPermissions['dcw-board']['edit-policy'] = true;
$wgGroupPermissions['dcw-board']['edit'] = true;
$wgGroupPermissions['dcw-board']['edit-main'] = true;
$wgGroupPermissions['dcw-board']['protect'] = true;
$wgGroupPermissions['dcw-board']['move'] = true;
$wgGroupPermissions['dcw-board']['editprotected'] = true;
$wgGroupPermissions['dcw-board']['edit-policy'] = true;
$wgGroupPermissions['dcw-board']['edit-main'] = true;
$wgGroupPermissions['dcw-board']['movefile'] = true;
$wgGroupPermissions['dcw-board']['createtalk'] = true;
$wgGroupPermissions['dcw-board']['userrights'] = true;
$wgGroupPermissions['dcw-board']['usermerge'] = true;
$wgGroupPermissions['dcw-board']['renameuser'] = true;
$wgGroupPermissions['dcw-board']['createaccount'] = true;
$wgGroupPermissions['dcw-board']['noratelimit'] = true;
$wgGroupPermissions['dcw-board']['requestips'] = true;
$wgGroupPermissions['dcw-board']['lookupcredentials'] = true;
$wgGroupPermissions['dcw-board']['delete'] = true;
$wgGroupPermissions['dcw-board']['editcontentmodel'] = true;
$wgAddGroups['dcw-board'] = array ( 'dcw-organisers' );
$wgRemoveGroups['dcw-board'] = array ( 'dcw-organisers' );
$wgGroupPermissions['dcw-board']['hideuser'] = true;
$wgGroupPermissions['dcw-board']['translate'] = true;
$wgGroupPermissions['dcw-board']['translate-messagereview'] = true;
$wgGroupPermissions['dcw-board']['translate-groupreview'] = true;
$wgGroupPermissions['dcw-board']['translate-import'] = true;
$wgGroupPermissions['dcw-board']['campaignevents-enable-registration'] = true;
$wgGroupPermissions['dcw-board']['campaignevents-organize-events'] = true;
$wgGroupPermissions['dcw-board']['create-resource'] = true;
$wgGroupPermissions['dcw-board']['edit-resource'] = true;


/* Tech Ambassadors priveleges */
$wgGroupPermissions['tech-ambassador']['editusercss'] = true;
$wgGroupPermissions['tech-ambassador']['edituserjson'] = true;
$wgGroupPermissions['tech-ambassador']['edituserjs'] = true;
$wgGroupPermissions['tech-ambassador']['editsitecss'] = true;
$wgGroupPermissions['tech-ambassador']['editsitejson'] = true;
$wgGroupPermissions['tech-ambassador']['editsitejs'] = true;
$wgGroupPermissions['tech-ambassador']['editinterface'] = true;

/* Trusted users priveleges */
$wgGroupPermissions['trusted-users']['edit'] = true;
$wgGroupPermissions['trusted-users']['createpage'] = true;
$wgGroupPermissions['trusted-users']['autopatrol'] = true;
$wgGroupPermissions['trusted-users']['upload'] = true;
$wgGroupPermissions['trusted-users']['createpage'] = true;
$wgGroupPermissions['trusted-users']['createclass'] = true;
$wgGroupPermissions['trusted-users']['move'] = true;
$wgGroupPermissions['trusted-users']['movefile'] = true;
$wgGroupPermissions['trusted-users']['move-categorypages'] = true;
$wgGroupPermissions['trusted-users']['move-subpages'] = true;
$wgGroupPermissions['trusted-users']['move-rootuserpages'] = true;
$wgGroupPermissions['trusted-users']['reupload-shared'] = true;
$wgGroupPermissions['trusted-users']['reupload'] = true;
$wgGroupPermissions['trusted-users']['sendemail'] = true;
$wgGroupPermissions['trusted-users']['applychangetags'] = true;
$wgGroupPermissions['trusted-users']['changetags'] = true;
$wgGroupPermissions['trusted-users']['edit-main'] = true;
$wgGroupPermissions['trusted-users']['translate'] = true;
$wgGroupPermissions['trusted-users']['translate-messagereview'] = true;
$wgGroupPermissions['trusted-users']['translate-groupreview'] = true;
$wgGroupPermissions['trusted-users']['translate-import'] = true;

/* Disable Crat' priveleges */
$wgGroupPermissions['bureaucrat']['confirmaccount-notify'] = false;
$wgGroupPermissions['bureaucrat']['createaccount'] = false;
$wgGroupPermissions['bureaucrat']['noratelimit'] = false;
$wgGroupPermissions['bureaucrat']['requestips'] = false;
$wgGroupPermissions['bureaucrat']['confirmaccount'] = false;
$wgGroupPermissions['bureaucrat']['lookupcredentials'] = false;
$wgGroupPermissions['bureaucrat']['userrights'] = false;
$wgGroupPermissions['bureaucrat']['renameuser'] = false;

/* Membership Facilitators priveleges */
$wgGroupPermissions['membership-facilitators']['confirmaccount-notify'] = true;
$wgGroupPermissions['membership-facilitators']['createaccount'] = true;
$wgGroupPermissions['membership-facilitators']['noratelimit'] = true;
$wgGroupPermissions['membership-facilitators']['requestips'] = true;
$wgGroupPermissions['membership-facilitators']['confirmaccount'] = true;
$wgGroupPermissions['membership-facilitators']['lookupcredentials'] = true;
$wgAddGroups['membership-facilitators'] = array ( 'trusted-users' );
$wgRemoveGroups['membership-facilitators'] = array ( 'trusted-users' );

$wgGroupPermissions['resource-person']['create-resource'] = true;
$wgGroupPermissions['resource-person']['edit-resource'] = true;

/* Graphic Intern priveleges */
$wgGroupPermissions['graphic-intern']['upload'] = true;
$wgGroupPermissions['graphic-intern']['movefile'] = true;
$wgGroupPermissions['graphic-intern']['autopatrol'] = true;

/* Founder priveleges */
$wgGroupPermissions['founder']['createpage'] = true;
$wgGroupPermissions['founder']['createtalk'] = true;
$wgGroupPermissions['founder']['lookupuser'] = true;
$wgGroupPermissions['founder']['edit'] = true;
$wgGroupPermissions['founder']['move'] = true;
$wgGroupPermissions['founder']['upload'] = true;
$wgGroupPermissions['founder']['autopatrol'] = true;
$wgGroupPermissions['founder']['autoconfirmed'] = true;
$wgGroupPermissions['founder']['viewsuppressed'] = true;
$wgGroupPermissions['founder']['delete'] = true;
$wgGroupPermissions['founder']['siteadmin'] = true;
$wgGroupPermissions['founder']['editsitecss'] = true; 

/* Elections */
$wgGroupPermissions['electionadmin']['securepoll-create-poll'] = true;
$wgGroupPermissions['electionadmin']['securepoll-edit-poll'] = true;
$wgGroupPermissions['electionadmin']['securepoll-view-voter-pii'] = true;

/* Event Organiser Privileges */
$wgGroupPermissions['dcw-organisers']['autopatrol'] = true;
$wgGroupPermissions['dcw-organisers']['createpage'] = true;
$wgGroupPermissions['dcw-organisers']['sendemail'] = true;
$wgGroupPermissions['dcw-organisers']['campaignevents-email-participants'] = true;
$wgGroupPermissions['dcw-organisers']['campaignevents-enable-registration'] = true;
$wgGroupPermissions['dcw-organisers']['campaignevents-organize-events'] = true;
$wgGroupPermissions['dcw-organisers']['campaignevents-delete-registration'] = true;
$wgGroupPermissions['dcw-organisers']['campaignevents-view-private-participants'] = true;
$wgGroupPermissions['dcw-organisers']['edit'] = true;
$wgGroupPermissions['dcw-organisers']['edit-main'] = true;

/* Disable Default Org' priveleges */
$wgGroupPermissions['event-organizer']['campaignevents-email-participants'] = false;
$wgGroupPermissions['event-organizer']['campaignevents-enable-registration'] = false;
$wgGroupPermissions['event-organizer']['campaignevents-organize-events'] = false;



$wgSecurePollSingleTransferableVoteEnabled = true;
$wgSecurePollUseLogging = true;

/* Generic priveleges */
$wgNotificationReplyName = 'No Reply - DCW';
$wgAutoWelcomeNewUsers = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgEmailConfirmToEdit = true;
#$wgGroupPermissions['*']['lookupuser'] = false;

/* Disabled groups*/
$wgExtensionFunctions[] = function() use ( &$wgGroupPermissions ) {
    unset( $wgGroupPermissions['upwizcampeditors'] ); 
    unset( $wgGroupPermissions['staff'] );
    unset( $wgGroupPermissions['push-subscription-manager'] ); 
    unset( $wgGroupPermissions['bot'] ); 
    unset( $wgGroupPermissions['interface-admin'] ); 
    unset( $wgGroupPermissions['suppress'] );
    unset( $wgGroupPermissions['bureaucrat'] );
    unset( $wgGroupPermissions['event-organizer'] );
};
unset( $wgRevokePermissions['bureaucrat'] );

/* Extra config goes here */
$wgArticlePath = '/$1';
unset( $wgFooterIcons['poweredby'] );
$wgCargoDBRowFormat = 'COMPRESSED';
$wgCargoAllowedSQLFunctions[] = 'IFNULL';
$wgCargoAllowedSQLFunctions[] = 'ADDDATE';
$wgWPBEnableHeadingOverride = false;

/*Json files go here */
$wgJsonConfigEnableLuaSupport = true; // required to use JsonConfig in Lua
$wgJsonConfigModels['Tabular.JsonConfig'] = 'JsonConfig\JCTabularContent';
$wgJsonConfigs['Tabular.JsonConfig'] = [ 
        'namespace' => 486, 
        'nsName' => 'Data',
        // page name must end in ".tab", and contain at least one symbol
        'pattern' => '/.\.tab$/',
        'license' => 'CC0-1.0',
        'isLocal' => false,
];

$wgJsonConfigModels['Map.JsonConfig'] = 'JsonConfig\JCMapDataContent';
$wgJsonConfigs['Map.JsonConfig'] = [ 
        'namespace' => 486,
        'nsName' => 'Data',
        // page name must end in ".map", and contain at least one symbol
        'pattern' => '/.\.map$/',
        'license' => 'CC0-1.0',
        'isLocal' => false,
];
$wgJsonConfigInterwikiPrefix = "commons";

$wgJsonConfigs['Tabular.JsonConfig']['remote'] = [ 
        'url' => 'https://commons.wikimedia.org/w/api.php'
];
$wgJsonConfigs['Map.JsonConfig']['remote'] = [
        'url' => 'https://commons.wikimedia.org/w/api.php'
];

/* Additional CSS commands */
$wgAllowSiteCSSOnRestrictedPages = true;
$wgMFAutodetectMobileView = true;
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgWikiEditorRealtimePreview = true;

$wgNamespacesWithSubpages = [
	NS_TALK => false,
	NS_USER => false,
	NS_USER_TALK => false,
	NS_MAIN => true
];


/*Thumb */
$wgGenerateThumbnailOnParse = true;
$wgThumbnailScriptPath = "$wgScriptPath/thumb.php";
$wgLocalFileRepo['transformVia404'] = true;
wfLoadExtension( 'ShortUrl' );
$wgShortUrlTemplate = '/dc-$1'; 
$wgUrlShortenerTemplate = '/dcw-$1';
$wgUrlShortenerEnableQrCode = true;
$wgUrlShortenerEnableSidebar = true;
$wgUrlShortenerAllowedDomains = true;
$wgUrlShortenerAllowedDomains = array(
	'(.*\.)?wikimedia\.org',
	'(.*\.)?wikipedia\.org',
	'(.*\.)?dcwwiki\.org', 
	'(.*\.)?forms\.gle',
	'(.*\.)?google\.com',
		'(.*\.)?linktr\.ee',
/*	'(.*\.)?whatsapp\.com',*/
/*	'(.*\.)?youtu\.be', */

);
$wgUrlShortenerApprovedDomains = array(
    '*.dcwwiki.org',
	'*.wikimedia.org',
	'*.wikipedia.org',
/*	'*.google.com', */
/*	'*.whatsapp.com', */
 /*   '*.youtu.be' */ );
$wgAllowUserJs = true;

/* Account Creation Stuff */

/* Auths */
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'WSOAuth' );
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['autocreateaccount'] = true;
$wgPluggableAuth_EnableLocalLogin = true;
$wgPluggableAuth_EnableAutoLogin = true;
$wgPluggableAuth_Config['Deoband Community Wikimedia'] = [
    'plugin' => 'WSOAuth',
    'data' => [
        'type' => 'mediawiki',
        'uri' => 'https://meta.wikimedia.org/w/index.php?title=Special:OAuth',
        'clientId' => $_ENV['MW_OAUTH_CLIENT_ID'] ?? '',
        'clientSecret' => $_ENV['MW_OAUTH_CLIENT_SECRET'] ?? '',
    ],
    'buttonLabelMessage' => 'dcw-mw-login-button-label'
];

$wgExtraNamespaces[NS_USER] = "Member";
$wgExtraNamespaces[NS_USER_TALK] = "Member_talk";

/*

wfLoadExtension( 'ConfirmAccount' );

$wgMakeUserPageFromBio = false;
 $wgAutoWelcomeNewUsers = false;
 $wgConfirmAccountRequestFormItems = [
 	'UserName'        => [ 'enabled' => true ],
 	'RealName'        => [ 'enabled' => true ],
 	'Biography'       => [ 'enabled' => true, 'minWords' => 30 ],
 	'AreasOfInterest' => [ 'enabled' => false ],
 	'CV'              => [ 'enabled' => false ],
 	'Notes'           => [ 'enabled' => true ],
 	'Links'           => [ 'enabled' => true ],
 	'TermsOfService'  => [ 'enabled' => true ],
 ];
 */
 $wgRestrictDisplayTitle = false;
 $wgHideInterlanguageLinks = true;
 $wgInterwikiMagic = true;
 $wgUseAutomaticEditSummaries = false;
$IP = realpath( "." );
$wgUploadDirectory = "{$IP}/images";
$wgUploadPath = "{$wgScriptPath}/images";
$wgTmpDirectory = "{$wgUploadDirectory}/temp";
$wgEnableScriptedUploads = true;
$wgSVGConverter = 'ImageMagick';
$wgCacheEpoch = '20260323000000'; // Today's date in YYYYMMDDHHMMSS format
$wgUseImageMagick = false;
$wgUsePathInfo = false;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgMaxImageArea = 100000000; // Increase this to handle larger PNGs
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoEngineConf['luastandalone']['luaPath'] = __DIR__ . '/extensions/Scribunto/includes/Engines/LuaStandalone/binaries/lua5_1_5_linux_64_generic/lua';
